// gen-stdlib runs `go list std` and generates a Go source file containing the
// set of user-importable standard-library import paths for the current
// toolchain. Regenerate on a Go version bump:
//
//	go generate ./internal/analyzer/golang/...
package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"slices"
	"sort"
	"strings"
	"text/template"
)

const outputPath = "stdlib_generated.go"

var tmpl = template.Must(
	template.New("stdlib").Parse(`// Code generated by gen-stdlib; DO NOT EDIT.

package golang

// stdlibPackages is the set of user-importable standard-library import paths
// for the Go toolchain that generated this file.
var stdlibPackages = map[string]struct{}{
{{- range .}}
	"{{.}}": {},
{{- end}}
}
`),
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "gen-stdlib: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	ctx := context.Background()

	out, err := exec.CommandContext(ctx, "go", "list", "std").Output()
	if err != nil {
		return fmt.Errorf("go list std: %w", err)
	}

	pkgs := parseStdlib(out)
	if len(pkgs) == 0 {
		return errors.New(
			"no standard-library packages found — go list std output may have changed",
		)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, pkgs); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt generated source: %w", err)
	}

	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outputPath, err)
	}

	fmt.Fprintf(os.Stderr, "gen-stdlib: wrote %d packages to %s\n", len(pkgs), outputPath)

	return nil
}

// parseStdlib extracts sorted, deduplicated import paths from `go list std`
// output, dropping vendored (vendor/...) and internal packages that user source
// cannot import — only public paths can appear as a dependency, so only they
// belong in the classifier's lookup set.
func parseStdlib(out []byte) []string {
	seen := make(map[string]struct{})

	for line := range strings.SplitSeq(strings.TrimSpace(string(out)), "\n") {
		pkg := strings.TrimSpace(line)
		if pkg == "" || !importable(pkg) {
			continue
		}

		seen[pkg] = struct{}{}
	}

	pkgs := make([]string, 0, len(seen))
	for pkg := range seen {
		pkgs = append(pkgs, pkg)
	}

	sort.Strings(pkgs)

	return pkgs
}

// importable reports whether a standard-library path can be imported by user
// source. Vendored paths are rewritten by the toolchain, and any path with an
// "internal" segment is importable only within its parent tree.
func importable(pkg string) bool {
	if strings.HasPrefix(pkg, "vendor/") {
		return false
	}

	return !slices.Contains(strings.Split(pkg, "/"), "internal")
}
