// Package hotspot computes change-frequency × instability hotspot scores via a Catmull-Rom curve.
package hotspot

import (
	"errors"
	"fmt"
	"sort"
)

// ControlPoint defines a point on the Catmull-Rom curve.
type ControlPoint struct {
	X, Y float64
}

// CatmullRomCurve evaluates a Catmull-Rom spline that passes through the given control points.
type CatmullRomCurve struct {
	points []ControlPoint // includes phantom endpoints
}

const (
	// minControlPoints is the minimum number of control points a curve needs.
	minControlPoints = 2
	// phantomEndpoints is the number of reflected phantom points added (one per end).
	phantomEndpoints = 2
	// catmullRomHalf is the 1/2 scalar in the uniform Catmull-Rom basis matrix.
	catmullRomHalf = 0.5
)

// NewCatmullRomCurve creates a Catmull-Rom curve from the given control points.
// Points must be sorted by X. At least 2 points are required.
// Phantom endpoints are generated by reflecting the first/last segment.
func NewCatmullRomCurve(points []ControlPoint) (*CatmullRomCurve, error) {
	if len(points) < minControlPoints {
		return nil, fmt.Errorf(
			"catmull-rom curve requires at least 2 control points, got %d",
			len(points),
		)
	}

	// Verify sorted by X
	for i := 1; i < len(points); i++ {
		//nolint:gosec // bounded loop: len(points) verified >= 2 above.
		if points[i].X <= points[i-1].X {
			return nil, errors.New("control points must be sorted by X with unique values")
		}
	}

	// Generate phantom endpoints by reflecting the first/last segment
	p := make([]ControlPoint, 0, len(points)+phantomEndpoints)

	// Phantom start: reflect P0-P1 before P0
	//nolint:gosec // len(points) verified >= 2 by guard above, points[0] and points[1] are valid.
	phantom0 := ControlPoint{
		X: 2*points[0].X - points[1].X,
		Y: 2*points[0].Y - points[1].Y,
	}
	p = append(p, phantom0)
	p = append(p, points...)

	// Phantom end: reflect Pn-1-Pn after Pn
	last := points[len(points)-1]
	prev := points[len(points)-2]
	phantomN := ControlPoint{
		X: 2*last.X - prev.X,
		Y: 2*last.Y - prev.Y,
	}
	p = append(p, phantomN)

	return &CatmullRomCurve{points: p}, nil
}

// Evaluate returns the Y value of the curve at the given X.
// X is clamped to the range of the original control points.
func (c *CatmullRomCurve) Evaluate(xValue float64) float64 {
	// The original points are at indices 1..len-2 (excluding phantoms)
	first := c.points[1]
	last := c.points[len(c.points)-phantomEndpoints]

	// Clamp xValue to the valid range
	if xValue <= first.X {
		return first.Y
	}

	if xValue >= last.X {
		return last.Y
	}

	// Find the correct segment. The original control points are at indices [1, len-2].
	// We need to find i such that points[i].X <= xValue < points[i+1].X
	// where i and i+1 are within the original points range.
	segIdx := min(max(sort.Search(len(c.points)-phantomEndpoints, func(i int) bool {
		return c.points[i+1].X > xValue
	}), 1), len(c.points)-phantomEndpoints-1)

	// Four points for the segment: P[i-1], P[i], P[i+1], P[i+2]
	point0 := c.points[segIdx-1]
	point1 := c.points[segIdx]
	point2 := c.points[segIdx+1]
	point3 := c.points[segIdx+2]

	// Parametric t in [0, 1] for this segment
	t := 0.0
	if point2.X != point1.X {
		t = (xValue - point1.X) / (point2.X - point1.X)
	}

	// Standard Catmull-Rom matrix formulation
	tSquared := t * t
	tCubed := tSquared * t

	//nolint:mnd // fixed Catmull-Rom uniform basis-matrix coefficients (2,3,4,5); naming them adds no clarity.
	y := catmullRomHalf * ((2 * point1.Y) +
		(-point0.Y+point2.Y)*t +
		(2*point0.Y-5*point1.Y+4*point2.Y-point3.Y)*tSquared +
		(-point0.Y+3*point1.Y-3*point2.Y+point3.Y)*tCubed)

	return y
}

// Default bell-curve control-point coordinates (peak at x = 0.5).
const (
	defaultBellBaselineY = 0.5
	defaultBellPeakX     = 0.5
)

// DefaultCurve returns a symmetric bell curve with peak at x=0.5.
// Control points: (0, 0.5), (0.5, 1), (1, 0.5).
func DefaultCurve() *CatmullRomCurve {
	c, _ := NewCatmullRomCurve([]ControlPoint{
		{X: 0, Y: defaultBellBaselineY},
		{X: defaultBellPeakX, Y: 1},
		{X: 1, Y: defaultBellBaselineY},
	})

	return c
}
