// gen-frameworks fetches Apple's technologies.json and generates a Go source
// file containing the set of system frameworks that support Swift.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"net/http"
	"os"
	"sort"
	"strings"
	"text/template"
)

const (
	technologiesURL = "https://developer.apple.com/tutorials/data/documentation/technologies.json"
	outputPath      = "frameworks_generated.go"
)

// technologiesDoc is the top-level structure of technologies.json.
type technologiesDoc struct {
	Sections []section `json:"sections"`
}

type section struct {
	Groups []group `json:"groups"`
}

type group struct {
	Technologies []technology `json:"technologies"`
}

type technology struct {
	Destination destination `json:"destination"`
	Languages   []string    `json:"languages"`
}

type destination struct {
	Identifier string `json:"identifier"`
}

// slugOverrides corrects module names for frameworks whose technologies.json
// identifier slug does not match the Swift import name — Apple lowercases or
// hyphenates some slugs ("carkey", "iokit", "simd-library") while their real
// module is PascalCase. Hand-maintained, like compilerModules; extend it when a
// slug-derived name fails to match a real import. The title field is not a
// usable alternative: it lowercases interior words ("Push to Talk") and adds
// marketing words ("Apple CryptoKit"), which breaks more names than it fixes.
var slugOverrides = map[string]string{
	"applicationservices": "ApplicationServices",
	"carkey":              "CarKey",
	"coreservices":        "CoreServices",
	"iokit":               "IOKit",
	"playgroundbluetooth": "PlaygroundBluetooth",
	"playgroundsupport":   "PlaygroundSupport",
	"simd-library":        "simd",
}

var tmpl = template.Must(
	template.New("frameworks").Parse(`// Code generated by gen-frameworks; DO NOT EDIT.

package swift

var systemFrameworks = map[string]struct{}{
{{- range .}}
	"{{.}}": {},
{{- end}}
}
`),
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "gen-frameworks: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	ctx := context.Background()

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, technologiesURL, nil)
	if err != nil {
		return fmt.Errorf("build request: %w", err)
	}

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return fmt.Errorf("fetch technologies.json: %w", err)
	}

	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("fetch technologies.json: HTTP %d", resp.StatusCode)
	}

	var doc technologiesDoc
	if err := json.NewDecoder(resp.Body).Decode(&doc); err != nil {
		return fmt.Errorf("parse technologies.json: %w", err)
	}

	seen := make(map[string]struct{})

	for _, sec := range doc.Sections {
		for _, grp := range sec.Groups {
			for _, tech := range grp.Technologies {
				if !hasSwift(tech.Languages) {
					continue
				}

				name := moduleName(tech.Destination.Identifier)
				if override, ok := slugOverrides[name]; ok {
					name = override
				}

				if name == "" {
					continue
				}

				seen[name] = struct{}{}
			}
		}
	}

	if len(seen) == 0 {
		return errors.New("no Swift frameworks found — the response format may have changed")
	}

	frameworks := make([]string, 0, len(seen))
	for name := range seen {
		frameworks = append(frameworks, name)
	}

	sort.Strings(frameworks)

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, frameworks); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt generated source: %w", err)
	}

	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outputPath, err)
	}

	fmt.Fprintf(
		os.Stderr,
		"gen-frameworks: wrote %d frameworks to %s\n",
		len(frameworks),
		outputPath,
	)

	return nil
}

func hasSwift(languages []string) bool {
	for _, lang := range languages {
		if strings.EqualFold(lang, "swift") {
			return true
		}
	}

	return false
}

func moduleName(identifier string) string {
	// identifier looks like "doc://com.apple.documentation/documentation/CoreData"
	idx := strings.LastIndex(identifier, "/")
	if idx < 0 || idx == len(identifier)-1 {
		return ""
	}

	return identifier[idx+1:]
}
