// Code generated by OTel Weaver. DO NOT EDIT.

// Package logschema provides type-safe structured log field constructors.
package logschema

import "log/slog"




// Language being analyzed
// Requirement level: REQUIRED
func UdaAnalyzerLanguage(val string) slog.Attr {
	return slog.String("uda.analyzer.language", val)
}


// Human-readable error description
// Requirement level: REQUIRED
func UdaErrorMessage(val string) slog.Attr {
	return slog.String("uda.error.message", val)
}


// File currently being analyzed
func UdaAnalyzerFile(val string) slog.Attr {
	return slog.String("uda.analyzer.file", val)
}


// Discovered config files (go.mod, Cargo.toml, pyproject.toml, Package.swift, package.json)
func UdaAnalyzerFilepaths(val []string) slog.Attr {
	return slog.Any("uda.analyzer.filepaths", val)
}


// Identified package/module names
func UdaAnalyzerPackages(val []string) slog.Attr {
	return slog.Any("uda.analyzer.packages", val)
}


// Boundary detection strategy in use
func UdaAnalyzerStrategy(val string) slog.Attr {
	return slog.String("uda.analyzer.strategy", val)
}


// File path where the error occurred
func UdaErrorPath(val string) slog.Attr {
	return slog.String("uda.error.path", val)
}


// Analysis phase where the error occurred
func UdaErrorPhase(val string) slog.Attr {
	return slog.String("uda.error.phase", val)
}


// Import alias
func UdaParseAlias(val string) slog.Attr {
	return slog.String("uda.parse.alias", val)
}


// Detected usage expression
func UdaParseExpression(val string) slog.Attr {
	return slog.String("uda.parse.expression", val)
}


// Detected import path
func UdaParseImport(val string) slog.Attr {
	return slog.String("uda.parse.import", val)
}


// Resolved module path
func UdaParseModule(val string) slog.Attr {
	return slog.String("uda.parse.module", val)
}


